server:
  port: 8898

spring:
  application:
    name: hw-auth
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:9004

eureka:
  client:
    service-url:
      defaultZone: http://server1:8080/eureka/

feign:
  hystrix:
    enabled: true