server:
  port: 8888

spring:
  application:
    name: hw-config
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:9004
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/

eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health


