server:
  port: 8899

spring:
  application:
    name: hw-admin
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:9004

eureka:
  client:
    service-url:
      defaultZone: http://server1:8080/eureka/

logging:
  level:
    com.adq.cloud.admin: debug