server:
  port: 9411
spring:
  application:
    name: hw-zipkin
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://server1:8080/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false